### ISSUE TITLE
Unhandled Exception: NoSuchMethodError: The method '[]' was called on null.

### ISSUE THREAD

**Issue by SayuZX** [frostnova721/animestream#10]

**Comment by SayuZX** [comment]
I/flutter: OperationException(linkException: ServerException(originalException: null, originalStackTrace: null, parsedResponse: Response(data: null, errors: [GraphQLError(message: The AniList API has been temporarily disabled due to severe stability issues. Please check the official AniList Discord for more information., locations: [ErrorLocation(line: 1, column: 1)], path: null, extensions: null)], context: Context({ResponseExtensions: Instance of 'ResponseExtensions'}), response {errors: [{message: The AniList API has been temporarily disabled due to severe stability issues. Please check the official AniList Discord for more information., status: 403, locations: [{line: 1, column: 1}]}], data: null})), graphqlErrors: [])

**Comment by frostnova721** [comment]
This is an issue from the anilist api! Not an issue from the client side
