### ISSUE TITLE
[Suggestion] Mal Support

### ISSUE THREAD

**Issue by Ahmedcodded** [frostnova721/animestream#11]
Currently it features support for anilist.co, _which is cool..._
But it would be great for it to have MAL support too! Cause some people only use MAL, (_while others use both_).
Thanks for the consideration!
(amazing project btw, starred!)

**Comment by frostnova721** [comment]
Would. It's a planned feature and I'm currently adding simkl. Will add MAL after that. 
Thanks for the feedback and the suggestion!

**Comment by frostnova721** [comment]
Closing the issue as it is implemented. Thanks for the suggestion, really appreciate it!
