### ISSUE TITLE
Bhay Hentai source when ?

### ISSUE THREAD

**Issue by Guru322** [frostnova721/animestream#3]
![Screenshot_2024-06-12-13-13-14-69_d3570c9a0825d1416bf5f3f87c7595ef](https://github.com/frostnova721/animestream/assets/106463398/90f8604c-7640-4932-8db5-a25cc92b15ac)
Can't watch my favourite anime 👊

**Comment by frostnova721** [comment]
😂 idk maybe some time

**Comment by Guru322** [comment]
raha nahi jaat aur , jaldi add kar
