### ISSUE TITLE
Playback Speed options in player

### ISSUE THREAD

**Issue by Aaxiruz** [frostnova721/animestream#8]
Dantotsu has many more playback feature, but I think a playback speed option like the one they have would be awesome, especially the cursed speeds

**Comment by frostnova721** [comment]
Do people actually use it? It's a planned feature tho! Thanks for the feedback

**Comment by Aaxiruz** [comment]
Yea very much, great way to just fast forward through expositions and I personally Dont get much time to watch anime so its a huge help
